package com.learning.java.orders.api;

import org.springframework.http.HttpStatus;
import org.springframework.web.bind.annotation.*;
import java.math.BigDecimal;
import java.util.*;

/** HTTP adapter for the order use cases; later modules move state into a service and repository. */
@RestController
@RequestMapping("/orders")
public final class OrderController {
    private final Map<String, OrderResponse> orders = new LinkedHashMap<>();

    // List.copyOf avoids exposing the controller's mutable map-backed collection to callers.
    @GetMapping public List<OrderResponse> list() { return List.copyOf(orders.values()); }
    @GetMapping("/{id}") public OrderResponse get(@PathVariable String id) { return Optional.ofNullable(orders.get(id)).orElseThrow(() -> new OrderNotFoundException(id)); }
    @PostMapping @ResponseStatus(HttpStatus.CREATED) public OrderResponse create(@RequestBody CreateOrderRequest request) {
        // IDs are generated by the server so clients cannot collide or overwrite existing orders.
        var order = new OrderResponse(UUID.randomUUID().toString(), request.customerId(), request.total(), "NEW");
        orders.put(order.id(), order); return order;
    }
    @PatchMapping("/{id}/status") public OrderResponse changeStatus(@PathVariable String id, @RequestBody StatusRequest request) {
        var previous = get(id); var updated = new OrderResponse(previous.id(), previous.customerId(), previous.total(), request.status()); orders.put(id, updated); return updated;
    }
    public record CreateOrderRequest(String customerId, BigDecimal total) { }
    public record StatusRequest(String status) { }
    public record OrderResponse(String id, String customerId, BigDecimal total, String status) { }
    @ResponseStatus(HttpStatus.NOT_FOUND) static final class OrderNotFoundException extends RuntimeException { OrderNotFoundException(String id) { super("Order not found: " + id); } }
}
